<?php

class PostTableSeeder extends Seeder {

	public function run()
	{

		$post= new Post();
		$post->title = 'Bacon!';
		$post->user_id = 1;
		$post->body = 'Bacon ipsum dolor amet kevin tri-tip shankle turkey pancetta ribeye. Filet mignon leberkas chuck cow turkey. Ball tip picanha kielbasa, brisket short loin ham capicola. Venison sausage salami bresaola shankle boudin ribeye ball tip chicken meatball beef pork belly short ribs pancetta strip steak. Leberkas hamburger kielbasa prosciutto meatloaf. Meatball chicken tongue, shankle fatback shank chuck. Turducken short loin ball tip, venison meatball alcatra shank pork loin beef fatback. Doner cupim jerky picanha turkey swine biltong pastrami capicola corned beef shank salami. Pork bresaola ball tip pig brisket beef ribs pork chop fatback jowl. Beef shank shoulder porchetta beef ribs picanha meatball short loin ball tip ham hock swine shankle. Ball tip flank frankfurter ham beef ribs. Ball tip cow strip steak ribeye. Pork brisket pig salami ground round pancetta drumstick ribeye short ribs. Sausage landjaeger bacon ground round salami jowl turkey ribeye. Tenderloin bresaola turducken, pork chop flank pastrami capicola tri-tip sausage tail kielbasa porchetta prosciutto. Venison pork belly pork loin, fatback tail brisket salami capicola sausage ribeye beef ribs pork chop andouille shoulder. Corned beef sirloin bacon, shank brisket pastrami ham ball tip salami spare ribs beef ribs venison shoulder bresaola. Pork belly pork pig, shank pork chop brisket picanha jerky shoulder pancetta short ribs hamburger rump. T-bone kevin ham tail biltong picanha. Corned beef prosciutto porchetta pastrami shankle hamburger turkey pork chop capicola tri-tip chicken pancetta bacon rump jerky. Jerky turducken kielbasa tongue strip steak ham bresaola cupim. Meatloaf swine pork chop ribeye, pig short ribs jowl alcatra. Jowl jerky biltong, boudin leberkas short ribs andouille. Bresaola meatloaf short ribs, ball tip turducken ham beef ribs strip steak bacon. Andouille ground round frankfurter shank salami cupim ham venison tri-tip chuck pork loin biltong fatback cow alcatra. Pork drumstick frankfurter short loin t-bone. Pork picanha cow meatloaf jowl kevin ball tip. Venison meatloaf leberkas, turducken brisket fatback meatball. Landjaeger cupim alcatra, spare ribs bresaola tri-tip filet mignon kevin brisket pancetta. Pork belly kevin t-bone beef ribs, shankle pork alcatra short ribs cow leberkas pastrami fatback jerky.';
		$post->img_url = '/img/bacon.jpg';
		$post->save();

		$post= new Post();
		$post->title = 'Cupcake!';
		$post->user_id = 3;
		$post->body = 'Cupcake ipsum dolor sit amet. Marshmallow cookie cake danish. Cookie cotton candy apple pie sesame snaps tootsie roll pastry. Powder cotton candy carrot cake chocolate muffin topping halvah soufflé ice cream. Bonbon bonbon jelly beans ice cream lemon drops. Liquorice liquorice liquorice croissant jujubes pudding chocolate cake cake powder. Sesame snaps chocolate bar tiramisu bear claw sweet cake halvah cheesecake cake. Pudding chupa chups apple pie liquorice cake topping. Bear claw oat cake apple pie topping chocolate lemon drops pudding. Bonbon tiramisu cake croissant cake pudding cookie. Jujubes soufflé lemon drops jelly beans oat cake carrot cake donut candy macaroon. Cake croissant candy. Oat cake ice cream donut soufflé gingerbread. Cake powder candy canes. Powder cotton candy carrot cake marshmallow. Cupcake cake sesame snaps cotton candy brownie. Chupa chups gingerbread soufflé macaroon oat cake icing. Soufflé chocolate cake candy. Tart liquorice brownie chocolate bar tootsie roll cake powder dragée tootsie roll. Soufflé pastry croissant pie ice cream powder cheesecake. Halvah caramels marzipan cupcake chocolate cake. Gummi bears biscuit topping candy canes. Tart marshmallow muffin marzipan dessert danish tart cake. Macaroon pudding jelly beans jelly beans. Chocolate macaroon gingerbread. Soufflé sugar plum fruitcake chocolate cake candy canes. Ice cream apple pie dessert jujubes dessert sugar plum ice cream danish. Oat cake pudding liquorice sesame snaps pudding jujubes cotton candy. Gummies tootsie roll toffee. Bonbon tootsie roll jelly candy canes pastry apple pie. Bear claw tiramisu candy canes liquorice oat cake chocolate bar. Icing toffee jelly. Biscuit brownie apple pie cheesecake lemon drops. Liquorice marshmallow liquorice sweet roll chocolate.Jelly beans cupcake tiramisu icing cotton candy ice cream pudding marshmallow gummi bears. Jelly-o marshmallow brownie. Sweet sweet croissant. Cake marshmallow jelly brownie liquorice. Icing cotton candy candy canes. Tiramisu tart soufflé. Donut gummi bears lemon drops jelly cake apple pie dragée sweet roll. Cheesecake powder sugar plum gingerbread candy canes bonbon. Tart sweet roll cotton candy.';
		$post->img_url = '/img/cupcake.jpg';
		$post->save();

		$post = new Post();
		$post->title = 'Samuel Jackson!';
		$post->user_id = 2;
		$post->body = 'My money\'s in that office, right? If she start giving me some bullshit about it ain\'t there, and we got to go someplace else and get it, I\'m gonna shoot you in the head then and there. Then I\'m gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I\'m talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand? Now that we know who you are, I know who I am. I\'m not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain\'s going to be? He\'s the exact opposite of the hero. And most times they\'re friends, like you and me! I should\'ve known way back when... You know why, David? Because of the kids. They called me Mr Glass.';
		$post->img_url = '/img/samuel.jpg';
		$post->save();

		$post = new Post();
		$post->title = 'Veggies!';
		$post->user_id = 1;
		$post->body = 'Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion daikon amaranth tatsoi tomatillo melon azuki bean garlic. Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini. Turnip greens yarrow ricebean rutabaga endive cauliflower sea lettuce kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter purslane kale. Celery potato scallion desert raisin horseradish spinach carrot soko. Lotus root water spinach fennel kombu maize bamboo shoot green bean swiss chard seakale pumpkin onion chickpea gram corn pea. Brussels sprout coriander water chestnut gourd swiss chard wakame kohlrabi beetroot carrot watercress. Corn amaranth salsify bunya nuts nori azuki bean chickweed potato bell pepper artichoke. Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery. Bunya nuts black-eyed pea prairie turnip leek lentil turnip greens parsnip. Sea lettuce lettuce water chestnut eggplant winter purslane fennel azuki bean earthnut pea sierra leone bologi leek soko chicory celtuce parsley jÃ­cama salsify. Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard.';
		$post->img_url = '/img/veggies.jpg';
		$post->save();		

		$post = new Post();
		$post->title = 'Cheese!';
		$post->user_id = 4;
		$post->body = 'Bocconcini babybel parmesan. Who moved my cheese brie macaroni cheese lancashire fondue danish fontina st. agur blue cheese paneer. Cream cheese cheeseburger goat camembert de normandie taleggio goat caerphilly the big cheese. Cheese slices who moved my cheese mozzarella say cheese cheddar parmesan bavarian bergkase parmesan. Paneer st. agur blue cheese cauliflower cheese. Goat camembert de normandie cheesy grin. Rubber cheese goat ricotta dolcelatte blue castello boursin croque monsieur cauliflower cheese. Melted cheese cheeseburger cheese on toast boursin monterey jack cheesecake swiss cheesecake. Cheese triangles cheese and biscuits boursin goat the big cheese cut the cheese cheese on toast dolcelatte. Smelly cheese cheesy grin danish fontina manchego. Stinking bishop caerphilly cheese on toast. Rubber cheese lancashire red leicester mascarpone fromage frais port-salut pecorino boursin. Swiss paneer squirty cheese boursin blue castello paneer monterey jack mascarpone. Boursin. Roquefort cheese triangles bavarian bergkase. Babybel fromage frais boursin cheesy grin caerphilly the big cheese cheese on toast jarlsberg. Babybel cheese slices blue castello st. agur blue cheese goat squirty cheese cheese slices queso. Fromage pecorino cheese and biscuits. Pepper jack stilton feta. Ricotta the big cheese boursin roquefort babybel the big cheese cheddar macaroni cheese. Jarlsberg cheese strings when the cheese comes out everybody\'s happy airedale chalk and cheese pecorino everyone loves emmental. Port-salut dolcelatte pepper jack gouda roquefort cheese and biscuits cheese and biscuits brie. Mozzarella melted cheese parmesan.';
		$post->img_url = '/img/cheese.jpg';
		$post->save();		

		$post = new Post();
		$post->title = 'Zombie!';
		$post->user_id = 5;
		$post->body = 'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead. Cum horribilem walking dead resurgere de crazed sepulcris creaturis, zombie sicut de grave feeding iride et serpens. Pestilentia, shaun ofthe dead scythe animated corpses ipsa screams. Pestilentia est plague haec decaying ambulabat mortuos. Sicut zeder apathetic malus voodoo. Aenean a dolor plan et terror soulless vulnerum contagium accedunt, mortui iam vivam unlife. Qui tardius moveri, brid eof reanimator sed in magna copia sint terribiles undeath legionis. Alii missing oculis aliorum sicut serpere crabs nostram. Putridi braindead odores kill and infect, aere implent left four dead. Lucio fulci tremor est dark vivos magna. Expansis creepy arm yof darkness ulnis witchcraft missing carnem armis Kirkman Moore and Adlard caeruleum in locis. Romero morbo Congress amarus in auras. Nihil horum sagittis tincidunt, zombie slack-jawed gelida survival portenta. The unleashed virus est, et iam zombie mortui ambulabunt super terram. Souless mortuum glassy-eyed oculos attonitos indifferent back zom bieapoc alypse. An hoc dead snow braaaiiiins sociopathic incipere Clairvius Narcisse, an ante? Is bello mundi z?';
		$post->img_url = '/img/zombie.jpg';
		$post->save();		

		$post = new Post();
		$post->title = 'Beer!';
		$post->user_id = 3;
		$post->body = 'The Dixie Beer inside a spudgun competes with a Jamaica Red Ale near the Sam Adams. For example, a Hazed and Infused indicates that a Stella Artois sells a bottle of beer inside another Left Hand Milk Stout to another Hefeweizen. A Mango Beer for a PBR makes love to a gravy like Ellis Island IPA. When an Ipswich Ale around a King Henry is dumbly flabby, the Stella Artois slurly gives the last beer to an Imperial Stout behind another Ellis Island IPA. A Corona Extra of some bottle is crazy. Some Left Hand Milk Stout A bud light about the Coors almost can be kind to the Coors inside a micro brew. The Home brew behind an ice house, a chain saw living with a bud light, and a Left Hand Milk Stout are what made America great! Some Sierra Nevada Pale Ale from the King Henry secretly avoids contact with some bottle of beer related to a hops. Sometimes a mug from a Brewers Reserve leaves, but a girl scout beyond a broken bottle always satiates a dorky grizzly beer! Another secretly unstable Avery IPA Any line dancer can find much coolness with the porter, but it takes a real bud light to slyly conquer a molten IPA. The Mango Beer secretly requires assistance from the scooby snack. The Dos Equis makes love to a Hops Alligator Ale. A whacked Citra Ninja makes love to the self-loathing bill. A college-educated Heineken A crank case behind a Long Trail Ale is tanked. For example, a discusting spudgun indicates that a wanker of the milwakees best gives the last beer to a Home brew around the stein. The greasy Wolverine Beer finds lice on a chain saw. Sometimes a Dos Equis beyond the ESB starts reminiscing about a lost buzz, but a mysterious Busch always eats a Guiness about a Heineken! Most people believe that a satellite brewery from a Fraoch Heather Ale ignores the Long Trail Ale about the Amarillo Pale Ale, but they need to remember how overwhelmingly a Miller near the monkey bite panics.';
		$post->img_url = '/img/beer.jpg';
		$post->save();	

	}
}